### ISSUE TITLE
Height Animation

### ISSUE THREAD

**Issue by newkind** [stephenscaff/read-smore#12]
Quick question about animating content block height. Do you have any ideas what would be the best way to animate the text after clicking the "less" button since the DOM elements that will be truncated are being removed instantly?

Thanks for the great script!

**Comment by stephenscaff** [comment]
Sorry for the late reply. 

I understand what you're getting at, but this script made the design decision to toggle between 2 states where the content is actually truncated - not just hidden. So, animating height wouldn't be easily feasible.

The script was built for larger production apps where height animations wouldn't be desirable - ie: user comments, production descriptions, etc.

If you need height animation, an easy move is to just set a max height on your content, hide the overflow, and transition between an arbitrarily large max-height on active state.

Closing this as the feature request isn't aligned with the lib.

Thanks for reaching out.
