### ISSUE TITLE
if maximum word count is not exceeded =  do nothing

### ISSUE THREAD

**Issue by reilldesign** [stephenscaff/read-smore#16]
Hi,
thanks for this extremely lightweight solution. We use this in a Joomla CMS blog override. Is there a way that the read more button only appears when the maximum word count is exceeded. In the other case truncating is not necessary. Sometimes there is only very short text

**Comment by stephenscaff** [comment]
Yep, you're correct. This is a bug.

I just pushed a fix to [fix/less-than-count](https://github.com/stephenscaff/read-smore/tree/fix/less-than-count).

I'll add some tests, merge and deploy it asap.

Thanks.

**Comment by stephenscaff** [comment]
Published update.
Take a look. Going to review a bit then close this.

**Comment by stephenscaff** [comment]
Okay, closing this now. 
Here's[ a code sandbox ](https://codesandbox.io/s/readsmore-2-0-tests-ucuz2f?file=/index.html) that tests 4 options: 
- Max Word and Chars count less than content, triggering the truncation. 
- Max Word and Chars count more than content, so we bail and do nothing.

Let me know if you have any other issues.
